export * from './dashboard-view';
export * from './manage-view';
export * from './sales-view';
export * from './orders-view';
export * from './employees-view';
export * from './manage-categories-view';
export * from './info-store-view';
export * from './manage-stores-view';
export * from './inventory-manage-view';
