name: CI

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.toml'
      - '.github/workflows/cd.yml'
      - '.github/workflows/ci.yml'
      - 'infrastructure/**'
      - '.env*'
      - '.gitignore'
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.toml'
      - '.github/workflows/cd.yml'
      - '.github/workflows/ci.yml'
      - 'infrastructure/**'
      - '.env*'
      - '.gitignore'
  workflow_dispatch:
    # allow manual trigger
    inputs:
      branch:
        description: 'Branch to build'
        required: false
        default: 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  # type-check:
  #   name: Type Check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'npm'

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run type check
  #       run: npm run type-check

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'npm'

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run tests
  #       run: npm run test

  notify:
    name: Send Webhook Notification
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    needs: [build, lint]
    if: always()
    steps:
      - name: Send CI notification
        if: always()
        env:
          BUILD_RESULT: ${{ needs.build.result }}
          LINT_RESULT: ${{ needs.lint.result }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_API_URL: ${{ github.api_url }}
        run: |
          # Derive overall workflow status from needed jobs
          if [ "$BUILD_RESULT" = "success" ] && [ "$LINT_RESULT" = "success" ]; then
            STATUS="success"
          elif [ "$BUILD_RESULT" = "cancelled" ] || [ "$LINT_RESULT" = "cancelled" ]; then
            STATUS="cancelled"
          elif [ "$BUILD_RESULT" = "failure" ] || [ "$LINT_RESULT" = "failure" ]; then
            STATUS="failure"
          else
            STATUS="cancelled"
          fi
          REPO="${{ github.repository }}"
          RUN_ID="${{ github.run_id }}"
          WORKFLOW="${{ github.workflow }}"
          BRANCH="${{ github.ref_name }}"
          COMMIT_SHA="${{ github.sha }}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          ACTOR="${{ github.actor }}"
          RUN_URL="https://github.com/$REPO/actions/runs/$RUN_ID"
          
          echo "CI completed for $REPO on branch $BRANCH"
          echo "- build: $BUILD_RESULT"
          echo "- lint: $LINT_RESULT"
          echo "- overall: $STATUS"
          echo "Run URL: $RUN_URL"
          echo "Commit: $COMMIT_SHA"
          echo "Commit Message: $COMMIT_MESSAGE"
          
          # Check webhook configuration - Try both naming conventions
          WEBHOOK_URL="${{ secrets.WEBHOOK_URL }}"
          WEBHOOK_SECRET="${{ secrets.WEBHOOK_SECRET }}"
          
          # Fallback to CI_WEBHOOK_URL if WEBHOOK_URL is not set
          if [ -z "$WEBHOOK_URL" ]; then
            WEBHOOK_URL="${{ secrets.CI_WEBHOOK_URL }}"
          fi
          
          if [ -z "$WEBHOOK_URL" ] || [ -z "$WEBHOOK_SECRET" ]; then
            echo "⚠️  Webhook not configured"
            echo "📝 To enable webhook notifications, add these to repository secrets:"
            echo "  - WEBHOOK_URL or CI_WEBHOOK_URL (webhook endpoint)"
            echo "  - WEBHOOK_SECRET (webhook secret key)"
            echo ""
            echo "🔍 Current secrets status:"
            echo "  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL != '' && 'SET' || 'NOT SET' }}"
            echo "  WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET != '' && 'SET' || 'NOT SET' }}"
            echo "  CI_WEBHOOK_URL: ${{ secrets.CI_WEBHOOK_URL != '' && 'SET' || 'NOT SET' }}"
          else
            echo "📡 Sending webhook notification..."
            echo "🔗 Webhook URL: $WEBHOOK_URL"
            # Ensure jq is available for safe JSON construction
            if ! command -v jq >/dev/null 2>&1; then
              echo "Installing jq..."
              sudo apt-get update -y >/dev/null 2>&1 || true
              sudo apt-get install -y jq >/dev/null 2>&1 || true
            fi

            # Fetch jobs for this run from GitHub API to include id and direct job URL
            JOBS_API_JSON=$(curl -s \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "$GITHUB_API_URL/repos/$REPO/actions/runs/$RUN_ID/jobs?per_page=100")

            # Build jobs array: [{id, name, result, url}]
            JOBS_JSON=$(echo "$JOBS_API_JSON" | jq '[.jobs[] | {id: .id, name: .name, result: (.conclusion // .status), url: .html_url}]')

            # Build JSON payload safely (handles newlines and quotes)
            PAYLOAD=$(jq -n \
              --arg workflow "$WORKFLOW" \
              --arg repo "$REPO" \
              --arg run_id "$RUN_ID" \
              --arg run_url "$RUN_URL" \
              --arg status "$STATUS" \
              --arg branch "$BRANCH" \
              --arg commit_sha "$COMMIT_SHA" \
              --arg commit_message "$COMMIT_MESSAGE" \
              --arg actor "$ACTOR" \
              --argjson jobs "$JOBS_JSON" \
              '{workflow_name:$workflow, repository:$repo, run_id:$run_id, run_url:$run_url, status:$status, jobs:$jobs, branch:$branch, commit_sha:$commit_sha, commit_message:$commit_message, actor:$actor}')

            echo ""
            echo "📋 Webhook payload to be sent:"
            echo "==============================="
            echo "$PAYLOAD" | jq '.' 2>/dev/null || echo "$PAYLOAD"
            echo "==============================="
            echo ""

            # Send webhook with error handling
            WEBHOOK_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
                 -H "Content-Type: application/json" \
                 -H "X-Webhook-Secret: $WEBHOOK_SECRET" \
                 -d "$PAYLOAD" "$WEBHOOK_URL")
            
            # Extract HTTP status code (last line)
            HTTP_STATUS=$(echo "$WEBHOOK_RESPONSE" | tail -n1)
            RESPONSE_BODY=$(echo "$WEBHOOK_RESPONSE" | head -n -1)
            
            if [ "$HTTP_STATUS" = "200" ]; then
              echo "✅ Webhook notification sent successfully!"
              echo "📊 Response: $RESPONSE_BODY"
            else
              echo "❌ Webhook notification failed with status: $HTTP_STATUS"
              echo "📊 Response: $RESPONSE_BODY"
              echo "🔗 Webhook URL: $WEBHOOK_URL"
            fi
          fi
